language: android
sudo: true

jdk:
  - oraclejdk8

android:
  components:
   - tools
   - build-tools-23.0.2
   - android-23
   - extra-android-m2repository
  licenses:
   - android-sdk-license-.+

branches:
  only:
   - develop
   - master

script: ./gradlew clean build checkstyle
